swagger: '2.0'
info:
  title: Utah Nanofab Interlocks API Proxy
  description: Enable and disable hardware and software interlocks
  version: "1.0.0"
host: {{ host }}
schemes:
  - https
  - http
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`  
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /proxy:
    post:
      security:
      - basicAuth: []
      summary: Forward on to another Interlock
      description: |
        Post to this url to reach another interlock
      parameters:
      - in: body
        name: body
        description: Config object that describes the request to proxy forward
        required: true
        schema:
          "$ref": "#/definitions/Proxy"
      responses:
        200:
          description: A description of state of interlock
          schema:
            $ref: '#/definitions/Status'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Proxy:
    required:
    - host
    - port
    - command
    properties:
      host:
        type: string
        example: example.com
      port:
        type: integer
        format: int64
      command:
        type: string
        enum:
        - status
        - sense
        - enable
        - disable
        - unlock
        - lock
      scheme:
        type: string
        enum:
        - http
        - https
      problems:
        type: integer
        format: int64
      shutdowns:
        type: integer
        format: int64
      username:
        type: string
      password:
        type: string

  Status:
    type: object
    properties:
      status:
        type: string
        description: Current status of interlock ("locked" or "unlocked")
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
